version: "3.7"

services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - GUAC_USER=yvv #optional
      - GUAC_PASS=2b542679dea6567d2c21c360345d2351 #optional
      - UMASK_SET=022 #optional
      - CLI_ARGS= #optional
    volumes:
      - ./books:/config
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped