version: "3.7"

services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - GUAC_USER=yvv #optional
      - GUAC_PASS=827ccb0eea8a706c4c34a16891f84e7b #optional
      - UMASK_SET=022 #optional
      - CLI_ARGS= #optional
    volumes:
      - ./books:/config
    ports:
      - 8080:8080
    restart: unless-stopped